# 用途：Kubernetes密钥配置文件，管理敏感信息
# 依赖文件：deployment.yaml
# 作者：后端开发团队
# 时间：2025-09-28 20:45:00

apiVersion: v1
kind: Secret
metadata:
  name: caddy-shopping-backend-secrets
  namespace: caddy-shopping
  labels:
    app: caddy-shopping-backend
    version: "1.0.0"
type: Opaque
data:
  # 数据库认证信息（base64编码）
  db-host: "bXlzcWwtc2VydmljZQ=="  # mysql-service
  db-port: "NDAwMA=="  # 4000 (TiDB默认端口)
  database-username: "cG9zdGdyZXM="  # postgres
  database-password: "c2VjdXJlLXBhc3N3b3Jk"  # secure-password
  use-tidb: "dHJ1ZQ=="  # true
  db-ssl: "ZmFsc2U="  # false
  
  # Redis认证信息
  REDIS_PASSWORD: "cmVkaXMtcGFzc3dvcmQ="  # redis-password
  
  # JWT密钥（生产环境应该使用更安全的密钥）
  JWT_SECRET_KEY: "eW91ci1zdXBlci1zZWN1cmUtanNvbi13ZWItdG9rZW4tc2VjcmV0LWtleQ=="  # your-super-secure-json-web-token-secret-key
  
  # API密钥
  API_KEY: "eW91ci1hcGkta2V5"  # your-api-key
  
  # 第三方服务密钥
  PAYMENT_GATEWAY_KEY: "cGF5bWVudC1nYXRld2F5LWtleQ=="  # payment-gateway-key
  EMAIL_SERVICE_KEY: "ZW1haWwtc2VydmljZS1rZXk="  # email-service-key