version: '3.8'

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve-test
    restart: unless-stopped
    ports:
      - "5080:5080"
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
      - ZO_DATA_DIR=/data
    volumes:
      - openobserve_data:/data
    networks:
      - openobserve_network

volumes:
  openobserve_data:
    driver: local

networks:
  openobserve_network:
    driver: bridge