# AI生成的代码质量门禁配置文件
# @ai-generated: 基于Claude 4 Sonnet生成的质量门禁配置

# 代码质量门禁配置
version: "1.0.0"
name: "Caddy Style Shopping Site Quality Gates"
description: "企业级代码质量门禁配置"

# ESLint配置
eslint:
  enabled: true
  config_file: ".eslintrc.js"
  max_warnings: 15  # 当前有10个警告，允许一些缓冲
  max_errors: 0     # 不允许任何错误
  fail_on_error: true
  fail_on_warning: false
  
# 代码覆盖率要求
coverage:
  enabled: true
  line_coverage_min: 80
  branch_coverage_min: 75
  function_coverage_min: 85
  statement_coverage_min: 80
  
# 代码复杂度限制
complexity:
  enabled: true
  cyclomatic_max: 10
  cognitive_max: 15
  nesting_depth_max: 4
  
# 代码重复检测
duplication:
  enabled: true
  max_percentage: 5
  min_lines: 10
  
# 安全扫描
security:
  enabled: true
  vulnerability_threshold: "medium"
  dependency_check: true
  secret_detection: true
  
# 性能要求
performance:
  enabled: true
  bundle_size_max_mb: 5
  load_time_max_ms: 3000
  lighthouse_score_min: 90
  
# 代码风格
code_style:
  enabled: true
  prettier_check: true
  naming_convention: true
  comment_coverage_min: 60
  
# 依赖管理
dependencies:
  enabled: true
  outdated_check: true
  vulnerability_check: true
  license_check: true
  allowed_licenses:
    - "MIT"
    - "Apache-2.0"
    - "BSD-3-Clause"
    - "ISC"
  
# Git提交要求
git:
  enabled: true
  commit_message_format: true
  branch_protection: true
  pr_review_required: true
  
# 构建要求
build:
  enabled: true
  build_success_required: true
  test_success_required: true
  no_build_warnings: false
  
# 文档要求
documentation:
  enabled: true
  readme_required: true
  api_docs_required: false
  changelog_required: true
  
# 通知配置
notifications:
  enabled: true
  on_failure: true
  on_success: false
  channels:
    - "console"
    - "file"
    
# 报告配置
reporting:
  enabled: true
  formats:
    - "json"
    - "html"
    - "markdown"
  output_dir: "./quality-reports"
  
# 豁免规则
exemptions:
  files:
    - "**/*.test.js"
    - "**/*.spec.js"
    - "**/demo/**"
    - "**/examples/**"
  rules:
    - "no-magic-numbers"  # 允许在配置文件中使用魔法数字
    
# 自定义规则
custom_rules:
  - name: "ai-generated-comment"
    description: "AI生成的代码必须包含来源注释"
    pattern: "@ai-generated"
    required: true
    
  - name: "security-review"
    description: "安全相关代码需要额外审查"
    files: "**/security/**"
    review_required: true
    
# 质量趋势跟踪
trends:
  enabled: true
  track_metrics:
    - "coverage"
    - "complexity"
    - "duplication"
    - "vulnerabilities"
  history_days: 30
  
# 自动修复
auto_fix:
  enabled: true
  safe_fixes_only: true
  rules:
    - "prettier"
    - "eslint-fixable"
    
# 集成配置
integrations:
  github_actions: true
  sonarqube: false
  codecov: false
  snyk: false