services:
  # OpenObserve服务
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: openobserve
    ports:
      - "5080:5080"
    environment:
      - ZO_ROOT_USER_EMAIL=admin@example.com
      - ZO_ROOT_USER_PASSWORD=Complexpass#123
      - ZO_DATA_DIR=/data
    volumes:
      - openobserve_data:/data
    restart: unless-stopped
    networks:
      - openobserve-network

  # Redis服务 (用于缓存)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - openobserve-network

volumes:
  openobserve_data:
    driver: local
  redis_data:
    driver: local

networks:
  openobserve-network:
    driver: bridge