# 本地环境的 Docker Compose 配置文件

version: '3.8'

services:
  # PostgreSQL 数据库
  postgres:
    image: postgres:15-alpine
    container_name: shopping-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=shopping_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secure_postgres_password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Redis 缓存
  redis:
    image: redis:7-alpine
    container_name: shopping-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local