groups:
  - name: application.rules
    rules:
      - alert: HighP95Latency
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, route)) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: P95 latency above 1s
          description: P95 latency exceeded 1s for route {{ $labels.route }} over 5m.

      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status_code=~"5.."}[5m])) / sum(rate(http_requests_total[5m])) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Error rate above 5%
          description: HTTP 5xx ratio exceeded 5% over 5m.

      - alert: TooManyActiveConnections
        expr: active_connections > 8000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Active connections above threshold
          description: Active connections exceeded 8000 over 5m.

      - alert: HighEventLoopLag
        expr: event_loop_lag_ms > 200
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: Event loop lag above 200ms
          description: Event loop lag exceeded 200ms over 5m.

      - alert: HighQPS
        expr: sum(rate(http_requests_total[5m])) > 5000
        for: 5m
        labels:
          severity: info
        annotations:
          summary: Throughput (QPS) above 5000
          description: Overall QPS exceeded 5000 over 5m.

      - alert: HighMemoryUsage
        expr: memory_usage_bytes > 1.5e9
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: Memory usage above 1.5GB
          description: Process resident memory usage exceeded 1.5GB over 10m.

      - alert: HighCPUUsage
        expr: cpu_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: CPU usage above 85%
          description: CPU usage percentage exceeded 85% over 5m.

      - alert: HighGCPauseP95
        expr: histogram_quantile(0.95, sum(rate(nodejs_gc_duration_seconds_bucket[5m])) by (le, gc_type)) > 0.2
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: GC pause P95 above 200ms
          description: Node.js GC pause P95 exceeded 200ms over 10m.

      - alert: HighDBQueryLatencyP95
        expr: histogram_quantile(0.95, sum(rate(db_query_duration_seconds_bucket[5m])) by (le, operation)) > 0.3
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: DB query latency P95 above 300ms
          description: Database query latency P95 exceeded 300ms for {{ $labels.operation }} over 5m.