version: '3.8'

services:
  email-verifier:
    build:
      context: ./email-verifier
      dockerfile: Dockerfile
    container_name: email-verifier-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      # 基础配置
      - PORT=8080
      - HOST=0.0.0.0
      
      # SMTP 配置（可选，需要 25 端口可用或代理）
      - ENABLE_SMTP_CHECK=false
      - SMTP_TIMEOUT=10s
      
      # 代理配置（如果需要）
      # - SOCKS_PROXY=socks5://user:pass@proxy:1080
      
      # 一次性域名自动更新
      - AUTO_UPDATE_DISPOSABLE=true
      - UPDATE_INTERVAL=24h
      
      # 日志级别
      - LOG_LEVEL=info
      
    volumes:
      # 持久化数据（如果需要）
      - email-verifier-data:/app/data
      
    networks:
      - email-verifier-network
      
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    # 资源限制
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Redis 缓存（可选，用于生产环境缓存）
  redis:
    image: redis:7-alpine
    container_name: email-verifier-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - email-verifier-network
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru

  # Nginx 反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: email-verifier-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    networks:
      - email-verifier-network
    depends_on:
      - email-verifier

volumes:
  email-verifier-data:
    driver: local
  redis-data:
    driver: local

networks:
  email-verifier-network:
    driver: bridge