# OpenObserve优化配置文件 - 阶段四优化版本
config:
  # HTTP服务器配置
  http:
    addr: "0.0.0.0:5080"
    cors:
      enabled: true
      allow_origins: ["http://localhost:3000", "http://localhost:80", "https://localhost:443"]
      allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
      allow_headers: ["Content-Type", "Authorization"]
    # 性能优化配置
    timeout: 300
    keep_alive: 75
    max_connections: 1024
  
  # 数据存储配置
  data:
    dir: "/data"
    cache:
      enabled: true
      max_size: 2048 # MB - 增加缓存大小
      cache_latest_files: true
    # 性能优化
    compact:
      enabled: true
      interval: "1h"
      max_file_size: "1GB"
    # 数据压缩
    compression: "gzip"
    # 内存优化
    memory:
      max_size: "2GB"
      cache_enabled: true
    
  # 日志配置
  log:
    level: "info"
    file: "/data/logs/openobserve.log"
    # 日志轮转
    rotation:
      enabled: true
      max_size: "100MB"
      max_files: 10
    
  # 告警配置
  alerts:
    enabled: true
    evaluation_interval: "30s"
    # 告警缓存优化
    cache:
      enabled: true
      ttl: "5m"
    
  # 指标配置
  metrics:
    enabled: true
    retention: "90d"
    # 指标性能优化
    cache:
      enabled: true
      max_size: "512MB"
    
  # 追踪配置
  tracing:
    enabled: true
    retention: "7d"
    # 追踪性能优化
    batch_size: 1000
    flush_interval: "10s"
    
  # 数据流配置 - 优化版本
  streams:
    - name: "application-logs"
      type: "logs"
      retention: "30d"
      # 流性能优化
      max_file_size: "256MB"
      compression: "gzip"
      index_enabled: true
    - name: "system-metrics"
      type: "metrics"
      retention: "90d"
      max_file_size: "128MB"
      compression: "gzip"
      index_enabled: true
    - name: "request-traces"
      type: "traces"
      retention: "7d"
      max_file_size: "256MB"
      compression: "gzip"
      index_enabled: true
    - name: "business-events"
      type: "logs"
      retention: "365d"
      max_file_size: "512MB"
      compression: "gzip"
      index_enabled: true
    - name: "error-logs"
      type: "logs"
      retention: "90d"
      max_file_size: "128MB"
      compression: "gzip"
      index_enabled: true
      
  # 查询性能优化
  query:
    # 查询缓存
    cache:
      enabled: true
      ttl: "10m"
      max_size: "1GB"
    # 查询限制
    max_query_time: "5m"
    max_result_size: "100MB"
    # 并发查询控制
    max_concurrent_queries: 10
    
  # 安全配置
  auth:
    # 基础认证（开发环境）
    basic_auth:
      enabled: false
    # 令牌认证
    token:
      enabled: true
      expiration: "24h"
      
  # 集群配置（单节点模式）
  cluster:
    enabled: false
    name: "openobserve-cluster"
    
  # 内存和CPU优化
  resource:
    # CPU限制
    cpu_limit: "2"
    # 内存限制
    memory_limit: "4GB"
    # 垃圾回收优化
    gc:
      enabled: true
      interval: "5m"