version: "3.8"
services:
  pd:
    image: pingcap/pd:v7.5.0
    container_name: tidb-pd
    command:
      - --name=pd
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd:2379
      - --advertise-peer-urls=http://pd:2380
      - --initial-cluster=pd=http://pd:2380
      - --data-dir=/data/pd
    ports:
      - "2379:2379"
    volumes:
      - pd-data:/data
    networks: [tidb-net]

  tikv:
    image: pingcap/tikv:v7.5.0
    container_name: tidb-tikv
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv:20160
      - --data-dir=/data/tikv
      - --pd=pd:2379
    depends_on: [pd]
    networks: [tidb-net]
    volumes:
      - tikv-data:/data

  tidb:
    image: pingcap/tidb:v7.5.0
    container_name: tidb-server
    command:
      - --store=tikv
      - --path=pd:2379
      - --advertise-address=tidb
      - -L
      - warn
    ports:
      - "4000:4000"
      - "10080:10080"
    depends_on: [pd, tikv]
    networks: [tidb-net]

networks:
  tidb-net:

volumes:
  pd-data:
  tikv-data:
