
# Prometheus配置用于OpenObserve指标收集
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'caddy-shopping'
    replica: 'prometheus-1'

# OpenObserve远程写入配置
remote_write:
  - url: "http://localhost:5080/api/caddy-shopping/system-metrics/_json"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*|process_.*|prometheus_.*'
        action: drop
      - source_labels: [__name__]
        regex: '(.*)'
        target_label: __name__
        replacement: 'metrics_${1}'
    headers:
      Content-Type: "application/json"
      Authorization: "Bearer ${OPENOBSERVE_TOKEN}"

# 告警管理器配置
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# 规则文件
rule_files:
  - "alert_rules.yml"

# 数据收集配置
scrape_configs:
  # Prometheus自身指标
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # 系统指标
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'localhost'

  # 应用指标
  - job_name: 'caddy-shopping-app'
    static_configs:
      - targets: ['localhost:3000']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'caddy-shopping-app'
      - source_labels: [__name__]
        regex: 'http_.*'
        target_label: __name__
        replacement: 'app_${1}'

  # Docker容器指标
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__name__]
        regex: 'container_.*'
        target_label: __name__
        replacement: 'docker_${1}'
