apiVersion: apps/v1
kind: Deployment
metadata:
  name: meilisearch
  namespace: search
  labels:
    app: meilisearch
    component: search-engine
spec:
  replicas: 2
  selector:
    matchLabels:
      app: meilisearch
  template:
    metadata:
      labels:
        app: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: getmeili/meilisearch:v1.7.4
        ports:
        - containerPort: 7700
        env:
        - name: MEILI_MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: search-secrets
              key: meili-master-key
        - name: MEILI_ENV
          value: "production"
        - name: MEILI_NO_ANALYTICS
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 7700
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 7700
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: meili-data
          mountPath: /meili_data
      volumes:
      - name: meili-data
        persistentVolumeClaim:
          claimName: meili-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: meilisearch-service
  namespace: search
  labels:
    app: meilisearch
spec:
  selector:
    app: meilisearch
  ports:
  - port: 7700
    targetPort: 7700
  type: ClusterIP