name: Backend OpenObserve Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-openobserve.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/backend-openobserve.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Lint Saved Queries
        run: node scripts/openobserve/lint-saved-queries.mjs

      - name: Install dependencies
        working-directory: backend
        run: npm ci

      - name: Run OpenObserve tests
        working-directory: backend
        run: npm run test:openobserve

      - name: Run OpenObserve contract tests
        working-directory: backend
        run: npm run test:contract:openobserve