name: "SBOM Generation & Image Signing"

on:
  workflow_dispatch:
    inputs:
      image_ref:
        description: "Container image reference (e.g., ghcr.io/OWNER/REPO-backend:SHA)"
        required: true
        type: string

permissions:
  contents: read
  id-token: write   # OIDC for keyless signing
  packages: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_REF: ${{ inputs.image_ref }}

jobs:
  sbom-and-sign:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Syft
        uses: anchore/sbom-action/download-syft@v1

      - name: Install Cosign
        uses: sigstore/cosign-installer@v3
        with:
          cosign-release: "v2.4.0"

      - name: Generate SBOM (SPDX JSON)
        run: |
          syft "${IMAGE_REF}" -o spdx-json > sbom.spdx.json
          test -s sbom.spdx.json

      - name: Sign Image with Cosign (OIDC keyless)
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: |
          cosign sign --yes "${IMAGE_REF}"

      - name: Install Grype
        uses: anchore/scan-action/download-grype@v3

      - name: Grype vulnerability scan (report)
        continue-on-error: true
        run: |
          grype "${IMAGE_REF}" -o table > grype-report.txt || true
          test -s grype-report.txt || echo "No grype output"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sbom-and-signing
          path: |
            sbom.spdx.json
            grype-report.txt