name: Timeout Evidence Generator

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: backend
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate timeout evidence
        run: npm run ci:timeout-evidence

      - name: Render Job Summary
        run: |
          node scripts/ci/render-timeout-summary.cjs | Out-File -Append -Encoding utf8 $env:GITHUB_STEP_SUMMARY

      - name: Collect latest evidence artifacts
        run: node scripts/ci/collect-latest-timeout-evidence.cjs

      - name: Upload timeout evidence artifacts
        uses: actions/upload-artifact@v4
        with:
          name: timeout-evidence-${{ github.run_id }}
          path: backend/test-output/latest/
          retention-days: 14